djtask/djtask/urls.py
from django.contrib import admin
from django.urls import path, include
from subject.views import ListaAsignaturas, CrearAsignatura, DetalleAsignatura, ActualizarAsignatura, EliminarAsignatura, Home
app_name = 'subject'
urlpatterns = [
    path('admin/', admin.site.urls),
    #home----------------------------
    path('',Home.as_view(), name = 'home'),
    #asignaturas---------------------
    path('asignaturas/', ListaAsignaturas.as_view(), name = 'subject_list'),
    path('asignaturas/crear/', CrearAsignatura.as_view(), name= 'create_subject'),
    path('asignaturas/<int:pk>/', DetalleAsignatura.as_view(), name='detail_subject'),
    path('asignaturas/<int:pk>/actualizar/', ActualizarAsignatura.as_view(), name='update_subject'),
    path('asignaturas/<int:pk>/eliminar/', EliminarAsignatura.as_view(), name= 'delete_subject'),
    #horarios------------------------
    path('schedules/', include('schedule.urls')),
    #actividades----------------------------------
    path('hworks/', include('hworks.urls')),





]   

 

djtask/schedule/urls.py
from django.urls import path
from .views import HorarioList, HorarioUpdate,HorarioCreate,HorarioDelete,HorarioDetail

app_name = 'schedule'

urlpatterns = [
    path('schedule_list/', HorarioList.as_view(), name='schedule_list'),
    path('create_schedule/',HorarioCreate.as_view(), name = 'create_schedule'),
    path('schedules/update/<int:pk>/',HorarioUpdate.as_view(),name = 'update_schedule'),
    path('schedules/delete/<int:pk>/', HorarioDelete.as_view(),name = 'delete_schedule' ),
    path('schedules/detail/<int:pk>/', HorarioDetail.as_view(), name='detail_schedule'),

]

djtask/schedule/models.py
#Modelo de todos los horarios
from django.db import models


# Create your models here.

class Horario(models.Model):
    DIA_SEMANA_CHOICES = [
        ('Lunes', 'Lunes'),
        ('Martes', 'Martes'),
        ('Miércoles', 'Miércoles'),
        ('Jueves', 'Jueves'),
        ('Viernes', 'Viernes'),
        ('Sábado', 'Sábado'),
        ('Domingo', 'Domingo'),

    ]
    
    
    asignatura = models.ForeignKey('subject.Asignatura', on_delete=models.CASCADE, related_name='horarios')  # 'subject.Asignatura' indica el modelo relacionado
    dia_semana = models.CharField(max_length=20, choices=DIA_SEMANA_CHOICES)
    hora_inicio = models.TimeField()
    hora_fin = models.TimeField()

    
    

    def __str__(self):
        return f"{self.asignatura.titulo} - {self.dia_semana} - {self.hora_inicio} - {self.hora_fin}"

djtask/schedule/forms.py
from django import forms
from django.core.exceptions import ValidationError
from schedule.models import Horario
from subject.models import Asignatura

# Definición del formulario HorarioForm basado en el modelo Horario.
class HorarioForm(forms.ModelForm):
    # Meta clase que proporciona metadatos al formulario HorarioForm.
    class Meta:
        model = Horario  # Indica que el formulario se basa en el modelo Horario.
        fields = ['asignatura', 'dia_semana', 'hora_inicio', 'hora_fin']  # Campos del modelo que se incluirán en el formulario.
        # Widgets personalizados para algunos de los campos del formulario.
        widgets = {
            'hora_inicio': forms.TimeInput(attrs={'type':'time'}),  # Se utiliza un widget de entrada de hora para hora_inicio.
            'hora_fin': forms.TimeInput(attrs={'type':'time'})  # Se utiliza un widget de entrada de hora para hora_fin.
        }

    # Método constructor de la clase HorarioForm.
    def __init__(self, *args, **kwargs):
        # Llamada al método constructor de la clase base (ModelForm) para inicializar el formulario.
        super(HorarioForm, self).__init__(*args, **kwargs)
        # Establece el queryset del campo 'asignatura' para incluir todas las instancias de Asignatura disponibles.
        self.fields['asignatura'].queryset = Asignatura.objects.all()
        # Personaliza la representación de cada instancia de Asignatura en el formulario.
        # Utiliza el título de la Asignatura como representación en lugar de la cadena devuelta por el método __str__.
        self.fields['asignatura'].label_from_instance = lambda obj: "%s" % obj.titulo

    # Método para la limpieza y validación de datos del formulario.
    def clean(self):
        # Llamada al método clean de la clase base para obtener los datos limpios.
        cleaned_data = super().clean()
        # Recupera la asignatura, día de la semana, hora de inicio y fin del formulario.
        dia_semana = cleaned_data.get('dia_semana')
        hora_inicio = cleaned_data.get('hora_inicio')
        hora_fin = cleaned_data.get('hora_fin')

        # Verifica que la hora de inicio sea anterior a la hora de fin.
        if hora_inicio and hora_fin:
            if hora_inicio >= hora_fin:
                # Añade el mensaje de error solo al campo hora_inicio.
                self.add_error('hora_inicio', "La hora de inicio debe ser anterior que la hora de fin")
            else:
                # Verifica que no haya solapamiento con otros horarios existentes.
                horarios_existentes = Horario.objects.filter(dia_semana=dia_semana)
                # Excluye el horario actual si estamos editando.
                if self.instance and self.instance.pk:
                    horarios_existentes = horarios_existentes.exclude(pk=self.instance.pk)

                for horario in horarios_existentes:
                    if (hora_inicio < horario.hora_fin and hora_fin > horario.hora_inicio):
                        # Añade el mensaje de error solo al campo hora_inicio.
                        self.add_error('hora_inicio', "Existe un horario existente dentro de este rango de horas, escoja otro por favor")
                        break

        # Retorna los datos limpios del formulario.
        return cleaned_data

djtask/schedule/views.py
from django.shortcuts import render
from django.views.generic import ListView , DetailView, CreateView, DeleteView, UpdateView
from schedule.models import Horario
from subject.models import Asignatura
from django.contrib import messages
from schedule.forms import HorarioForm
from django.urls import reverse_lazy,reverse
from django.http import HttpResponseRedirect
# Create your views here.

class HorarioList(ListView):
    model = Horario
    template_name = 'schedule_list.html'
    context_object_name = 'schedules'
    
    def get_queryset(self):
        # Ordenar los horarios primero por día de la semana y luego por hora de inicio
        return Horario.objects.all().order_by('dia_semana', 'hora_inicio')

    
       

class HorarioDetail(DetailView):
    model = Horario
    template_name = 'schedule_detail.html'
    context_object_name = 'schedule'



class HorarioCreate(CreateView):
    model = Horario
    form_class = HorarioForm
    template_name = 'create_schedule.html'
    success_url = reverse_lazy('schedule:schedule_list')

    

   


class HorarioDelete(DeleteView):
    model = Horario
    template_name = 'delete_schedule.html'
    success_url =  reverse_lazy('schedule:schedule_list')



class HorarioUpdate(UpdateView):
    model = Horario
    template_name = 'update_schedule.html'
    fields = ['asignatura', 'dia_semana', 'hora_inicio', 'hora_fin']
    success_url = reverse_lazy('schedule:schedule_list')

djtask/schedule/templates/create_schedule.html
{% extends 'base.html' %}

{% block title %}Crear Horario - {{ block.super }}{% endblock %}

{% block content %}
  <h2>Crear Nuevo Horario</h2>
  <form method="post">
    {% csrf_token %}
    <!-- Se elimina el bucle que muestra todos los errores para evitar duplicados en la parte superior -->
    {{ form.non_field_errors }} <!-- Si quieres mostrar errores que no están asociados a un campo específico -->
    <div class="fieldWrapper">
      {{ form.asignatura.errors }}
      {{ form.asignatura.label_tag }} {{ form.asignatura }}
    </div>
    <div class="fieldWrapper">
      {{ form.dia_semana.errors }}
      {{ form.dia_semana.label_tag }} {{ form.dia_semana }}
    </div>
    <div class="fieldWrapper">
      {{ form.hora_inicio.label_tag }} {{ form.hora_inicio }}
    </div>
    <div class="fieldWrapper">
      {{ form.hora_fin.label_tag }} {{ form.hora_fin }}
    </div>
    <div class="fieldWrapper">
      {{ form.hora_inicio.errors }}
      {{ form.hora_fin.errors }}
    </div>

    <button type="submit" class="btn btn-primary">Crear Horario</button>
  </form>
{% endblock %}

djtask/schedule/templates/delete_schedule.html
{% extends 'base.html' %}

{% block title %}Eliminar Horario - {{ block.super }}{% endblock %}

{% block content %}
  <h2>Eliminar Horario</h2>
  <p>¿Estás seguro de que quieres eliminar este horario?</p>
  <p><strong>Asignatura:</strong> {{ horario.asignatura.titulo }}</p>
  <p><strong>Día de la Semana:</strong> {{ horario.dia_semana }}</p>
  <p><strong>Hora de Inicio:</strong> {{ horario.hora_inicio }}</p>
  <p><strong>Hora de Fin:</strong> {{ horario.hora_fin }}</p>
  <form method="post" action="{% url 'schedule:delete_schedule' horario.pk %}" style="display: inline;">

    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Confirmar Eliminación</button>
  </form>
  <a href="{% url 'schedule:schedule_list' %}" class="btn btn-secondary">Cancelar</a>
{% endblock %}

djtask/schedule/templates/schedule_detail.html
{% extends 'base.html' %}

{% block title %}Detalles del Horario - {{ block.super }}{% endblock %}

{% block content %}
  <h2>Detalles del Horario</h2>
  <p><strong>Asignatura:</strong> {{ schedule.asignatura.titulo }}</p>
  <p><strong>Día de la Semana:</strong> {{ schedule.dia_semana }}</p>
  <p><strong>Hora de Inicio:</strong> {{ schedule.hora_inicio }}</p>
  <p><strong>Hora de Fin:</strong> {{ schedule.hora_fin }}</p>

  <a href="{% url 'schedule:update_schedule' schedule.pk %}" class="btn btn-primary">Editar</a>

  <form method="post" action="{% url 'schedule:delete_schedule' schedule.pk %}" style="display: inline;">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar</button>
  </form>
{% endblock %}

djtask/schedule/templates/schedule_list.html
{% extends 'base.html' %}

{% block title %}Lista de Horarios - {{ block.super }}{% endblock %}

{% block content %}
<style>
  /* Estilos para alinear correctamente los datos en la tabla */
  .table-horarios th, .table-horarios td {
    text-align: left; /* Alinea el texto a la izquierda */
    padding: 8px; /* Espaciado dentro de las celdas */
    vertical-align: middle; /* Alinea verticalmente el contenido en el medio de la celda */
    white-space: nowrap; /* Asegura que el texto no se pase a la siguiente línea */
  }
  .table-horarios th {
    position: sticky; /* Hace que la cabecera de la tabla sea fija al hacer scroll */
    top: 0;
    background: #fff;
    white-space: normal; /* Permite que los títulos de las columnas se ajusten si es necesario */
  }
  /* Ajusta el ancho de las columnas según sea necesario */
  .table-horarios .columna-dia {
    width: 15%; /* Ajusta el ancho de la columna del día */
  }
  .table-horarios .columna-hora-inicio, .table-horarios .columna-hora-fin {
    width: 10%; /* Ajusta el ancho de las columnas de hora */
  }
</style>
<h2>Lista de Horarios</h2>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped table-horarios">
                <thead>
                    <tr>
                        <th class="columna-dia">Día</th>
                        <th>Asignatura</th> 
                        <th>Profesor</th>
                        <th class="columna-hora-inicio">Hora de Inicio</th>
                        <th class="columna-hora-fin">Hora de Fin</th>
                        <th>Modalidad</th>
                        <th>Tipo de Asignatura</th>
                        <th>URL Clases Grabadas</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for horario in schedules %}
                        <tr>
                            <td>{{ horario.dia_semana }}</td>
                            <td><a href="{% url 'schedule:detail_schedule' horario.pk %}">{{ horario.asignatura.titulo }}</a></td>
                            <td>{{ horario.asignatura.profesor }}</td>
                            <td>{{ horario.hora_inicio }}</td>
                            <td>{{ horario.hora_fin }}</td>
                            <td>{{ horario.asignatura.modalidad }}</td>
                            <td>{{ horario.asignatura.tipo_asignatura }}</td>
                            <td>
                                {% if horario.asignatura.url_clases_grabadas %}
                                    <a href="{{ horario.asignatura.url_clases_grabadas }}" target="_blank">Ver Clases</a>
                                {% else %}
                                    No Disponible
                                {% endif %}
                            </td>
                            <td>
                                <a href="{% url 'schedule:update_schedule' horario.pk %}" class="btn btn-primary btn-sm">Editar</a>
                                <a href="{% url 'schedule:delete_schedule' horario.pk %}" class="btn btn-danger btn-sm">Eliminar</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<a href="{% url 'schedule:create_schedule' %}" class="btn btn-primary">Crear nuevo horario</a>
{% endblock %}

djtask/schedule/templates/update_schedule.html
{% extends 'base.html' %}

{% block title %}Actualizar Horario - {{ block.super }}{% endblock %}

{% block content %}
  <h2>Actualizar Horario</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Actualizar Horario</button>
  </form>
{% endblock %}