djtask/djtask/urls.py
from django.contrib import admin
from django.urls import path, include
from subject.views import ListaAsignaturas, CrearAsignatura, DetalleAsignatura, ActualizarAsignatura, EliminarAsignatura, Home
app_name = 'subject'
urlpatterns = [
    path('admin/', admin.site.urls),
    #home----------------------------
    path('',Home.as_view(), name = 'home'),
    #asignaturas---------------------
    path('asignaturas/', ListaAsignaturas.as_view(), name = 'subject_list'),
    path('asignaturas/crear/', CrearAsignatura.as_view(), name= 'create_subject'),
    path('asignaturas/<int:pk>/', DetalleAsignatura.as_view(), name='detail_subject'),
    path('asignaturas/<int:pk>/actualizar/', ActualizarAsignatura.as_view(), name='update_subject'),
    path('asignaturas/<int:pk>/eliminar/', EliminarAsignatura.as_view(), name= 'delete_subject'),
    #horarios------------------------
    path('schedules/', include('schedule.urls')),
    #actividades----------------------------------
    path('hworks/', include('hworks.urls')),





]   

 

djtask/hworks/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from hworks.views import ActividadesList, ActividadesCreate,ActividadesUpdate,ActividadesDetail,ActividadDelete

app_name = 'hworks'

urlpatterns = [
    path('hworks/activity_list/', ActividadesList.as_view(), name='activity_list'),
    path('hworks/create_activity/', ActividadesCreate.as_view(), name='create_activity'),
    path('hworks/update/<int:pk>/', ActividadesUpdate.as_view(), name='update_activity'),
    path('hworks/delete/<int:pk>/', ActividadDelete.as_view(), name='delete_activity'),
    path('hworks/detail/<int:pk>/', ActividadesDetail.as_view(), name='activity_detail'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djtask/schedule/urls.py
from django.urls import path
from .views import HorarioList, HorarioUpdate,HorarioCreate,HorarioDelete,HorarioDetail

app_name = 'schedule'

urlpatterns = [
    path('schedule_list/', HorarioList.as_view(), name='schedule_list'),
    path('create_schedule/',HorarioCreate.as_view(), name = 'create_schedule'),
    path('schedules/update/<int:pk>/',HorarioUpdate.as_view(),name = 'update_schedule'),
    path('schedules/delete/<int:pk>/', HorarioDelete.as_view(),name = 'delete_schedule' ),
    path('schedules/detail/<int:pk>/', HorarioDetail.as_view(), name='detail_schedule'),

]

djtask/subject/urls.py
# Url para gestión de enlaces entre asignatiuras académicas
# Permite administrar enlaces del modulo asignaturas


"""
URL configuration for djtask project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from schedule.views import ListaAsignaturas, CrearAsignatura, DetalleAsignatura, ActualizarAsignatura, EliminarAsignatura, Home


app_name = 'subject'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',Home.as_view(), name = 'home'),
    path('asignaturas/', ListaAsignaturas.as_view(), name = 'subject_list'),
    path('asignaturas/crear/', CrearAsignatura.as_view(), name= 'create_subject'),
    path('asignaturas/<int:pk>/', DetalleAsignatura.as_view(), name='detail_subject'),
    path('asignaturas/<int:pk>/actualizar/', ActualizarAsignatura.as_view(), name='update_subject'),
    path('asignaturas/<int:pk>/eliminar/', EliminarAsignatura.as_view(), name= 'delete_subject'),
 

]
    


    

djtask/subject/models.py
# Modelo para gestión de asignaturas académicas
# Permite administrar materias con información de profesores y horarios

from django.db import models


# Create your models here.
class Asignatura(models.Model):
    TIPO_ASIGNATURA_CHOICES = [
        ('Practica','Practica'),
        ('Teorica', 'Teorica'),
    ]

    MODALIDAD_CHOICES = [
        ('Virtual','Virtual'),
        ('Presencial','Presencial'),
    ]

    
    # Lógica que utiliza Horario

  

    titulo = models.CharField(max_length=100)
    profesor = models.CharField(max_length = 100)
    descripcion = models.TextField(blank = True)
    tipo_asignatura = models.CharField(max_length = 40, choices = TIPO_ASIGNATURA_CHOICES)
    modalidad = models.CharField(max_length = 20, choices = MODALIDAD_CHOICES)
    url_clases_grabadas = models.URLField(null = True, blank = True)

   
     

    def __str__(self):
        return self.titulo  # Simplemente retorna el título

    def get_horarios_display(self):
        horarios = self.horarios.all()
        if horarios:
            horario_str = ", ".join([f"{horario.dia_semana}:{horario.hora_inicio}--{horario.hora_fin}" for horario in horarios])
            return f"{self.titulo} - {horario_str}"
        else:
            return f"{self.titulo} - Horario no registrado"
    

djtask/subject/forms.py
from django import forms
from subject.models import Asignatura

class AsignaturaForm(forms.ModelForm):
    class Meta:
        model = Asignatura
        fields = ['titulo','profesor','descripcion', 'tipo_asignatura','modalidad','url_clases_grabadas']
        

djtask/subject/views.py
from django.db.models.query import QuerySet
from django.views.generic import ListView,CreateView, DetailView,UpdateView,DeleteView, TemplateView
from django.shortcuts import render, get_object_or_404,redirect
from django.urls import reverse_lazy, reverse
from subject.models import  Asignatura
from schedule.models import Horario

# Create your views here.

class ListaAsignaturas(ListView):
    model = Asignatura
    template_name = 'subject_list.html'
    context_object_name = 'subjects'

    def get_queryset(self):
        asignaturas = super().get_queryset()
        for asignatura in asignaturas:
            horarios = asignatura.horarios.all()
            # Crear una lista de cadenas de horario o una lista vacía si no hay horarios
            horarios_list = [f"{horario.dia_semana} {horario.hora_inicio}-{horario.hora_fin}" for horario in horarios] if horarios else []
            # Asigna la lista de cadenas de horario al atributo 'horarios_list' de la asignatura
            asignatura.horarios_list = horarios_list
        return asignaturas
    

class CrearAsignatura(CreateView):
    model = Asignatura
    fields = ['titulo', 'profesor', 'descripcion', 'tipo_asignatura', 'modalidad', 'url_clases_grabadas']
    template_name = 'create_subject.html'
    success_url = reverse_lazy('subject_list')

class DetalleAsignatura(DetailView):
    model = Asignatura
    template_name = 'detail_subject.html'
    context_object_name = 'subject'

class ActualizarAsignatura(UpdateView):
    model = Asignatura
    template_name = 'update_subject.html'
    fields = ['titulo','profesor','descripcion','tipo_asignatura','modalidad','url_clases_grabadas']
    success_url = reverse_lazy('subject_list')

class EliminarAsignatura(DeleteView):
    model = Asignatura
    template_name = 'delete_subject.html'
    success_url = reverse_lazy('subject_list')



class Home(TemplateView):
    template_name = 'home.html'

djtask/subject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mi Aplicación{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <!-- Agrega aquí cualquier otra hoja de estilos CSS necesaria -->
</head>
<body>
    <header>
        <h1>Mi Aplicación</h1>
    </header> 
    <nav>
        <ul>
            <li><a href="{% url 'home' %}"><i class="fas fa-home"></i> Inicio</a></li>
            <li><a href="{% url 'subject_list' %}"><i class="fas fa-book"></i> Asignaturas</a></li>
            <li><a href="{% url 'schedule:schedule_list' %}"><i class="fas fa-clock"></i> Horarios</a></li>
            <li><a href="{% url 'hworks:activity_list' %}"><i class="fas fa-tasks"></i> Tareas</a></li>

            <!-- Agrega aquí más enlaces para otras secciones si es necesario -->
        </ul>
    </nav>
    
    <main>
        {% block content %}{% endblock %}
    </main>

    <!-- Agrega aquí cualquier script JavaScript necesario -->

</body>
</html>

djtask/subject/templates/create_subject.html
{% extends 'base.html' %}

{% block title %}Crear Asignatura - {{ block.super }}{% endblock %}

{% block content %}
  <h2>Crear Nueva Asignatura</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Crear Asignatura</button>
  </form>
{% endblock %}

djtask/subject/templates/delete_subject.html
{% extends 'base.html' %}

{% block title %}Eliminar Asignatura - {{ block.super }}{% endblock %}

{% block content %}
  <h2>Eliminar Asignatura</h2>
  <p>¿Estás seguro de que deseas eliminar "{{ object }}"?</p>
  <form method="post" action="{% url 'delete_subject' object.pk %}">
    {% csrf_token %}
    <button type="submit">Sí</button>
  </form>
  <a href="{% url 'subject_list' %}">No</a>
{% endblock %}

djtask/subject/templates/detail_subject.html
{% extends 'base.html' %}

{% block title %}Detalles de la Asignatura - {{ subject.titulo }}{% endblock %}

{% block content %}
  <h2>Detalles de la Asignatura</h2>
  <ul>
    <li><strong>Título:</strong> {{ subject.titulo }}</li>
    <li><strong>Profesor:</strong> {{ subject.profesor }}</li>
    <li><strong>Descripción:</strong> {{ subject.descripcion }}</li>
    <li><strong>Tipo de Asignatura:</strong> {{ subject.tipo_asignatura }}</li>
    <li><strong>Modalidad:</strong> {{ subject.modalidad }}</li>
    <li><strong>URL de Clases Grabadas:</strong> {{ subject.url_clases_grabadas|default:"Sin registrar" }}</li>
    <!-- Agregar más detalles si es necesario -->
  </ul>

  <!-- Botones para eliminar y editar -->
  <a href="{% url 'delete_subject' subject.pk %}"><button>Eliminar</button></a>
  <a href="{% url 'update_subject' subject.pk %}"><button>Editar</button></a>
{% endblock %}

djtask/subject/templates/home.html
{% extends 'base.html' %}


{% block title %}Inicio - {{ block.super }}{% endblock %}

{% block content %}
    <h2>Bienvenido a Mi Aplicación</h2>
    <p>Selecciona una opción del menú de arriba.</p>
{% endblock %}

djtask/subject/templates/subject_list.html
{% extends 'base.html' %}

{% block title %}Lista de Asignaturas - {{ block.super }}{% endblock %}

{% block content %}
<style>
  /* Estilos para la tabla */
  .table-asignaturas th, .table-asignaturas td {
    padding: 8px; /* Espaciado interno en celdas */
    text-align: left; /* Alineación del texto a la izquierda */
    vertical-align: top; /* Alineación vertical en la parte superior */
    white-space: nowrap; /* Evita que el contenido se divida en varias líneas */
  }
  .table-asignaturas th {
    background-color: #f8f9fa; /* Color de fondo para los encabezados de tabla */
    position: sticky;
    top: 0;
  }
  .table-asignaturas td.horarios {
    white-space: normal; /* Permite que los horarios se muestren en líneas separadas */
    max-width: 200px; /* Máximo ancho para la columna de horarios */
  }
  .table-asignaturas td.acciones {
    white-space: nowrap; /* Mantiene las acciones en una sola línea */
  }
</style>

<h2>Lista de Asignaturas</h2>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped table-asignaturas">
        <thead>
          <tr>
            <th>Título</th>
            <th>Profesor</th>
            <th>Descripción</th>
            <th>Tipo</th>
            <th>Modalidad</th>
            <th>URL Clases Grabadas</th>
            <th>Horario</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          {% for asignatura in subjects %}
          <tr>
            
            <td class="nowrap"><a href="{% url 'detail_subject' asignatura.pk %}">{{ asignatura.titulo }}</a></td>
            <td>{{ asignatura.profesor }}</td>
            <td>{{ asignatura.descripcion }}</td>
            <td>{{ asignatura.tipo_asignatura }}</td>
            <td>{{ asignatura.modalidad }}</td>
            <td>{{ asignatura.url_clases_grabadas|default:"No Disponible" }}</td>
            <td class="horarios">
              {% for horario in asignatura.horarios_list %}
              {{ horario }}<br>
              {% endfor %}
            </td>
            <td class="acciones">
              <a href="{% url 'update_subject' asignatura.pk %}" class="btn btn-primary btn-sm">Editar</a>
              <a href="{% url 'delete_subject' asignatura.pk %}" class="btn btn-danger btn-sm">Eliminar</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

<a href="{% url 'create_subject' %}" class="btn btn-primary">Crear nueva asignatura</a>
{% endblock %}

djtask/subject/templates/update_subject.html
{% extends 'base.html' %}

{% block title %}Actualizar Asignatura - {{ block.super }}{% endblock %}

{% block content %}
  <h2>Actualizar Asignatura</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}  <!-- Esto mostrará los campos del formulario como párrafos -->
    <button type="submit">Guardar cambios</button>
  </form>
{% endblock %}