djtask/djtask/urls.py
from django.contrib import admin
from django.urls import path, include
from subject.views import ListaAsignaturas, CrearAsignatura, DetalleAsignatura, ActualizarAsignatura, EliminarAsignatura, Home
app_name = 'subject'
urlpatterns = [
    path('admin/', admin.site.urls),
    #home----------------------------
    path('',Home.as_view(), name = 'home'),
    #asignaturas---------------------
    path('asignaturas/', ListaAsignaturas.as_view(), name = 'subject_list'),
    path('asignaturas/crear/', CrearAsignatura.as_view(), name= 'create_subject'),
    path('asignaturas/<int:pk>/', DetalleAsignatura.as_view(), name='detail_subject'),
    path('asignaturas/<int:pk>/actualizar/', ActualizarAsignatura.as_view(), name='update_subject'),
    path('asignaturas/<int:pk>/eliminar/', EliminarAsignatura.as_view(), name= 'delete_subject'),
    #horarios------------------------
    path('schedules/', include('schedule.urls')),
    #actividades----------------------------------
    path('hworks/', include('hworks.urls')),





]   

 

djtask/hworks/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from hworks.views import ActividadesList, ActividadesCreate,ActividadesUpdate,ActividadesDetail,ActividadDelete

app_name = 'hworks'

urlpatterns = [
    path('hworks/activity_list/', ActividadesList.as_view(), name='activity_list'),
    path('hworks/create_activity/', ActividadesCreate.as_view(), name='create_activity'),
    path('hworks/update/<int:pk>/', ActividadesUpdate.as_view(), name='update_activity'),
    path('hworks/delete/<int:pk>/', ActividadDelete.as_view(), name='delete_activity'),
    path('hworks/detail/<int:pk>/', ActividadesDetail.as_view(), name='activity_detail'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djtask/hworks/models.py
#modelo de todas las tareas
from django.db import models
from subject.models import Asignatura

# Create your models here.

class Actividades(models.Model):
    TIPO_CHOICES = [
        ('Tarea','Tarea'),
        ('Taller','Taller'),        
        ('Exposicion','Exposicion'),
        ('TrabajoExperimental','Trabajo Experimental'),        
    ]
    
    PRIORIDAD_CHOICES = [
        ('Baja','Baja'),
        ('Media','Media'),
        ('Alta','Alta'),
    ]
    
    tipo = models.CharField(max_length=20, choices=TIPO_CHOICES)
    titulo = models.CharField(max_length=100)   
    asignatura = models.ForeignKey(Asignatura, on_delete=models.CASCADE, related_name='actividades_subject')
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    notas = models.TextField(blank=True)
    recursos = models.FileField(upload_to='recursos/', blank=True, null=True)
    enlaces = models.URLField(blank=True)
    fecha_limite = models.DateField()
    hora_limite = models.TimeField(blank=False, null=False)
    prioridad = models.CharField(max_length=20, choices=PRIORIDAD_CHOICES)
    calificacion = models.FloatField(null=True, blank=True)
    tiempo_restante = models.DurationField(blank=True, null=True, editable=False)  # Nuevo campo para el tiempo restante

    def __str__ (self):
        return self.titulo


class Leccion(models.Model):

    PRIORIDAD_CHOICES = [
        ('Baja','Baja'),
        ('Media','Media'),
        ('Alta','Alta'),
    ]

    fecha_creacion = models.DateTimeField(auto_now_add = True)
    asignatura = models.ForeignKey(Asignatura, on_delete = models.CASCADE,related_name='leccion_subject')
    titulo = models.CharField(max_length = 100)
    notas = models.TextField(blank = True)
    fecha_limite = models.DateTimeField()
    tiempo_restante = models.DurationField(blank=True, null=True)  # Nuevo campo para el tiempo restante
    enlaces = models.URLField(blank = True)
    recursos = models.FileField(upload_to='recursos/', blank=True, null=True)
    prioridad = models.CharField(max_length = 20, choices = PRIORIDAD_CHOICES)
    calificacion = models.FloatField(null = True, blank = True) 

    def __str__(self):
        return self.titulo
    

class Examen(models.Model):

    PRIORIDAD_CHOICES = [
        ('Baja','Baja'),
        ('Media','Media'),
        ('Alta','Alta'),
    ]
    
    asignatura = models.ForeignKey(Asignatura, on_delete = models.CASCADE,related_name = 'examen_subject')   
    fecha_creacion = models.DateTimeField(auto_now_add = True)
    fecha_limite = models.DateTimeField()
    titulo = models.CharField(max_length = 100)
    notas = models.TextField(blank = True)
    recursos = models.FileField()
    enlaces = models.URLField(blank = True)
    prioridad = models.CharField(max_length = 20, choices = PRIORIDAD_CHOICES)
    calificacion = models.FloatField(null = True, blank = True) 

    def __str__(self):
        return self.titulo

djtask/hworks/forms.py
from django import forms
from hworks.models import Actividades
from subject.models  import Asignatura


class ActividadesForm(forms.ModelForm):
    class Meta:
        model = Actividades
        exclude = ['tiempo_restante']

    # Método constructor de la clase HorarioForm.
    def __init__(self, *args, **kwargs):
        # Llamada al método constructor de la clase base (ModelForm) para inicializar el formulario.
        super(ActividadesForm, self).__init__(*args, **kwargs)
        # Establece el queryset del campo 'asignatura' para incluir todas las instancias de Asignatura disponibles.
        self.fields['asignatura'].queryset = Asignatura.objects.all()
        # Personaliza la representación de cada instancia de Asignatura en el formulario.
        # Utiliza el título de la Asignatura como representación en lugar de la cadena devuelta por el método __str__.
        self.fields['asignatura'].label_from_instance = lambda obj: "%s" % obj.titulo

djtask/hworks/views.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from django.shortcuts import render
from django.urls import reverse_lazy
from hworks.forms import ActividadesForm
from django.utils import timezone
    
from datetime import datetime, time
from hworks.models import Actividades, Leccion, Examen
# Create your views here.




class ActividadesCreate(CreateView):
    model = Actividades
    form_class = ActividadesForm
    template_name = 'create_activity.html'
    success_url = reverse_lazy('hworks:activity_list')




class ActividadesList(ListView):
    model = Actividades
    template_name = 'activity_list.html'
    context_object_name = 'activity_list'

    
class ActividadesDetail(DetailView):
    model = Actividades
    template_name = 'activity_detail.html'
    context_object_name = 'activity'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Obtener el objeto de actividad
        activity = self.get_object()
        
        # Agregar fecha límite y hora límite al contexto
        context['fecha_limite'] = activity.fecha_limite.strftime('%Y-%m-%d')
        context['hora_limite'] = activity.hora_limite.strftime('%H:%M')
        
        return context    




class ActividadesUpdate(UpdateView):
    model = Actividades
    template_name = 'activity_update.html'
    fields = [
        'tipo',
        'titulo',
        'asignatura',
        'notas',
        'recursos',
        'enlaces',
        'fecha_limite',
        'hora_limite',
        'prioridad',
        'calificacion',
        ]
    exclude = ['fecha_creacion','tiempo_restante']
    success_url = reverse_lazy('hworks:activity_list')

    def get_success_url(self):
        return reverse_lazy('hworks:activity_list')

class ActividadDelete(DeleteView):
    model = Actividades
    template_name = 'delete_activity.html'
    success_url = reverse_lazy('hworks:activity_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['activity'] = self.get_object()  # Agregar el objeto de la actividad al contexto
        return context

djtask/hworks/templates/activity_detail.html
<!-- activity_detail.html -->
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h1>Detalles de la Actividad</h1>
  <div class="actividad" data-fechalimite="{{ activity.fecha_limite|date:'Y-m-d' }}" data-horalimite="{{ activity.hora_limite|time:'H:i' }}">
    <!-- Información de la actividad -->
    Tipo: {{ activity.tipo }}<br>
    Título: {{ activity.titulo }}<br>
    Asignatura: {{ activity.asignatura }}<br>
    Profesor: {{ activity.asignatura.profesor }}<br>
    Fecha de Creación: {{ activity.fecha_creacion|date:"d/m/Y H:i" }}<br>
    Fecha Límite: {{ activity.fecha_limite|date:"d/m/Y" }} {{ activity.hora_limite|time:"H:i" }}<br>
    Tiempo Restante: <span class="tiempo-restante"></span><br> <!-- Aquí se mostrará el tiempo restante -->
    Prioridad: {{ activity.prioridad }}<br>
    <!-- Botón para editar actividad -->
    <a href="{% url 'hworks:update_activity' activity.pk %}">Editar</a>
    <!-- Botón para eliminar actividad -->
    <a href="{% url 'hworks:delete_activity' activity.pk %}">Eliminar</a>
  </div>

  <!-- Incluir el archivo JavaScript de tiempo_restante.js -->
  <script src="{% static 'tareas/tiempo_restante.js' %}"></script>
{% endblock %}

djtask/hworks/templates/activity_list.html
<!-- activity_list.html -->
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h1>Lista de Actividades</h1>
  <ul>
    {% for activity in activity_list %}
      <li class="actividad" data-fechalimite="{{ activity.fecha_limite|date:'Y-m-d' }}" data-horalimite="{{ activity.hora_limite|time:'H:i' }}">
        <a href="{% url 'hworks:activity_detail' activity.pk %}">{{ activity.titulo }}</a><br>
        Tipo: {{ activity.tipo }}<br>
        Asignatura: {{ activity.asignatura }}<br>
        Profesor: {{ activity.asignatura.profesor }}<br>
        Fecha de Creación: {{ activity.fecha_creacion|date:"d/m/Y H:i" }}<br>
        {% if activity.fecha_limite %}
          {% if activity.hora_limite %}
            Fecha Límite: {{ activity.fecha_limite|date:"d/m/Y" }} {{ activity.hora_limite|time:"H:i" }}<br>
          {% else %}
            Fecha Límite: {{ activity.fecha_limite|date:"d/m/Y" }}<br>
          {% endif %}
        {% endif %}
        Tiempo Restante: <span class="tiempo-restante"></span><br> <!-- Aquí se mostrará el tiempo restante -->
        <li>Prioridad: {{ activity.prioridad }}</li>
        {% if activity.calificacion %}
          <li>Calificación: {{ activity.calificacion }}</li>
        {% endif %}
        <!-- Botón para editar actividad -->
        <a href="{% url 'hworks:update_activity' activity.pk %}">Editar</a>
        <!-- Botón para eliminar actividad -->
        <a href="{% url 'hworks:delete_activity' activity.pk %}">Eliminar</a>                          
      </li>
    {% empty %}
      <li>No hay actividades disponibles</li>
    {% endfor %}
  </ul>
  <a href="{% url 'hworks:create_activity' %}">Crear nueva actividad</a>


  <!-- Incluir el archivo JavaScript de tiempo_restante.js -->
  <script src="{% static 'tareas/tiempo_restante.js' %}"></script> 

{% endblock %}

djtask/hworks/templates/activity_update.html
{% extends 'base.html' %}

{% block content %}
  <h1>Actualizar Actividad</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar Cambios</button>
  </form>
{% endblock %}

djtask/hworks/templates/create_activity.html
{% extends 'base.html' %}

{% block content %}
<h1>Crear Actividad</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Guardar</button>
</form>
{% endblock %}

djtask/hworks/templates/delete_activity.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h1>Eliminar Actividad</h1>
  <p>¿Estás seguro de que deseas eliminar la actividad "{{ activity.titulo }}"?</p>
  <div class="actividad" data-fechalimite="{{ activity.fecha_limite|date:'Y-m-d' }}" data-horalimite="{{ activity.hora_limite|time:'H:i' }}">
    <ul>
      <li>Tipo: {{ activity.tipo }}</li>
      <li>Título: {{ activity.titulo }}</li>
      <li>Asignatura: {{ activity.asignatura }}</li>
      <li>Profesor: {{ activity.asignatura.profesor }}</li>
      <li>Fecha de Creación: {{ activity.fecha_creacion|date:"d/m/Y H:i" }}</li>
      <li>Fecha Límite: {{ activity.fecha_limite|date:"d/m/Y" }} {{ activity.hora_limite|time:"H:i" }}</li>
      <li>Tiempo Restante: <span class="tiempo-restante"></span></li> <!-- Aquí se mostrará el tiempo restante -->
      <li>Prioridad: {{ activity.prioridad }}</li>
      {% if activity.calificacion %}
        <li>Calificación: {{ activity.calificacion }}</li>
      {% endif %}
    </ul>
    <form method="post">
      {% csrf_token %}
      <button type="submit">Eliminar</button>
    </form>
    <a href="{% url 'hworks:activity_list' %}">Cancelar</a>
  </div>
  
  <!-- Incluir el archivo JavaScript de tiempo_restante.js -->
  <script src="{% static 'tareas/tiempo_restante.js' %}"></script>
{% endblock %}